#!/usr/bin/ksh 
#########################################################################################
#
# Description:
#
# jobopsdsa000002 - delete the INSTOR_TOKEN data older than 2 days
#                    
#
#########################################################################################
#
# Exit Codes:
#
# 0 - Job completed successfully
# Non 0 - Job failed
#
#########################################################################################
# Implementation History:
#-------------------------------------------------------------------------------
#  Date        | Implemented by    |    Reason
#-------------------------------------------------------------------------------
# July 30 2020 | leipr             | Initial Version  
#########################################################################################


#########################################################################################
# Setup the HostCapture environment
#########################################################################################
FPATH=/apps/local/functions:$FPATH
export FPATH

# setup job environment passing jobname as a parm ($0)
ctfs_setup_env_java8 $0

# Set the log file name. Override the setting from the setup_env
LOGFNAME=$LOGDIR/$PROGNAME

#-- write logging records --
ctfs_logger "--begin jobopsdsa000002--"

# next line tells where the Tivoli job output can be found
ctfs_logger "UNISON_STDLIST is $UNISON_STDLIST"

#Set APP_PATH to current location
APP_PATH=/apps/ctalapps/dsaAcxiomBatch


# add libraries for this job to the CLASSPATH created in ctfs_setup_env
CLASSPATH=$CLASSPATH:$APP_PATH/dsa_acxiom_batch.jar:$APP_PATH/ojdbc6-11.2.0.3.jar:.
ctfs_logger "CLASSPATH is $CLASSPATH"

#########################################################################################
# Invoke the Java application to delete the instore token data
#########################################################################################

ctfs_logger "Invoking java application to delete the instore token data..."

java -Xms256M -Xmx1024M com.ctfs.dsa.batch.DSAInstoreTokenBatch
rc=$?

if test $rc -ne 0
then
	if test $rc -eq 1
	then
		ctfs_logger "$PROGNAME failed - SQL Exception while trying to extract data from DB" Warning
		exit $rc
	fi
	if test $rc -eq 2
	then
		ctfs_logger "$PROGNAME failed - DB Failure Exception while trying to extract data from DB" Warning
		exit $rc
	fi

else
   ctfs_logger "$PROGNAME successfully deleted the INSTOR_TOKEN data"
fi

#########################################################################################
# Delete old records older than 2 days
#########################################################################################
find $LOGDIR -name "`basename $LOGFNAME`*" -mtime +15 -exec rm -f {} \;

#########################################################################################
# End of Job
#########################################################################################
ctfs_logger "------jobopsdsa000002 ends-------" 
ctfs_archive_log

exit $rc