CREATE TABLE WEBIC_OWNER.CUSTOMERTRANSACTION_HIST 
   (
    TRANSACTIONID VARCHAR(128 ) NOT NULL , 
	PROFILEID VARCHAR(128 ) NOT NULL , 
	EMAIL VARCHAR(60 ) NOT NULL , 
	FIRSTNAME VARCHAR(40 ), 
	LASTNAME VARCHAR(40 ), 
	ADDRESSLINE1 VARCHAR(40 ), 
	ADDRESSLINE2 VARCHAR(40 ), 
	CITY VARCHAR(24 ), 
	PROVINCE VARCHAR(3 ), 
	POSTALCODE VARCHAR(6 ), 
	PHONENUMBER VARCHAR(10 ), 
	LOYALTYNUMBER VARCHAR(16), 
	TRANSACTIONDATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL , 
	LOYALTYPROGRAM VARCHAR(128 ), 
	REQUESTINGSYSTEM VARCHAR(128 ) NOT NULL , 
	 CONSTRAINT XPKWEBICCUSTTRANHIST PRIMARY KEY (TRANSACTIONID) 
   );
   
CREATE SYNONYM WEBIC_APP.CUSTOMERTRANSACTION_HIST FOR WEBIC_OWNER.CUSTOMERTRANSACTION_HIST;

GRANT  SELECT,INSERT,UPDATE,DELETE ON WEBIC_OWNER.CUSTOMERTRANSACTION_HIST TO  WEBIC_APP;  

GRANT  SELECT,INSERT,UPDATE,DELETE ON WEBIC_OWNER.CUSTOMERTRANSACTION_HIST TO  WEBIC_MAINT;
  
GRANT  SELECT ON WEBIC_OWNER.CUSTOMERTRANSACTION_HIST TO ANALYST_MKAD;
  
GRANT SELECT ON WEBIC_OWNER.CUSTOMERTRANSACTION_HIST TO WEBIC_READ;